# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment

# Specify Python and Node.js versions
[phases.setup]
    nixPkgs = ['python39', 'python39Packages.pip', 'nodejs_20', 'npm']

# Install Python dependencies for the backend
[phases.python-deps]
    dependsOn = ['setup']
    cmds = [
        'cd backend && python3.9 -m pip install --upgrade pip',
        'cd backend && python3.9 -m pip install -r requirements.txt'
    ]

# Run database migrations
[phases.db-migrations]
    dependsOn = ['python-deps']
    cmds = [
        'cd backend && python3.9 -m alembic upgrade head',
        'cd backend && python3.9 create_admin.py'
    ]

# Install npm dependencies with legacy peer deps
[phases.npm]
    dependsOn = ['db-migrations']
    cmds = ['npm install --legacy-peer-deps']

# Build the frontend
[phases.build]
    dependsOn = ['npm']
    cmds = ['npm run build']

# download caddy from nix
[phases.caddy]
    dependsOn = ['build'] # make sure this phase runs after the build phase
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4 - https://github.com/NixOS/nixpkgs/commit/ba913eda2df8eb72147259189d55932012df6301
    nixPkgs = ['caddy'] # install caddy as a nix package

# format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy'] # make sure this phase runs after the 'caddy' phase so that we know we have caddy downloaded
    cmds = ['caddy fmt --overwrite Caddyfile'] # format the Caddyfile to fix any formatting inconsistencies

# start the caddy web server and the FastAPI backend
[start]
    cmd = '(cd backend && python3.9 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &) && exec caddy run --config Caddyfile --adapter caddyfile 2>&1'